# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_shoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Human')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Shoe')),
            ],
        ),
    ]
